image: docker:latest

variables:
  IMAGE_NAME: goshare
  CI_IMAGE: $CI_REGISTRY_IMAGE:latest


stages:
  - build
  - test
  - deploy

build:
  tags:
    - docker-build
  stage: build
  only:
    - main
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_IMAGE .
    - docker push $CI_IMAGE

test:
  stage: test
  only:
    - main
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_IMAGE
    - docker run $CI_IMAGE python3 /src/commander.py
    - docker run $CI_IMAGE python3 /src/worker.py
  when: manual
  
deploy:
  stage: deploy
  image: portainer/kubectl-shell:latest
  only:
    - main
  before_script:
    - mkdir ~/.kube/
    - echo $KUBE_CONFIG | base64 -d > ~/.kube/config
    #- sed -i "s/registry.le37.tw\/le37\/goshare\/goshare:latest/${CI_IMAGE//\//\\/}/g" deployment.yaml
  script:
    - kubectl --kubeconfig ~/.kube/config apply -f deployment.yaml -n le37tw
