---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goshare-deployment
spec:
  selector:
    matchLabels:
      app: goshare
  replicas: 1
  template:
    metadata:
      labels:
        app: goshare
    spec:
      containers:
      - name: goshare-commander
        image: registry.le37.tw/default/goshare/goshare:latest
        command: ["sh","-c","/entrypoint.sh python3 /src/commander.py"]
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 5
      - name: goshare-worker
        image: registry.le37.tw/default/goshare/goshare:latest
        command: ["sh","-c","/entrypoint.sh python3 /src/worker.py"]
        livenessProbe:
          exec:
            command:
            - python ./src/healthcheck.py
          initialDelaySeconds: 30
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: goshare
spec:
  selector:
    app: goshare
  ports:
    - protocol: TCP
      port: 80
